# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title The probability density of standard Laplace distribution using Rcpp
#' @description The probability density of standard Laplace distribution using Rcpp
#' @param x the value of the variable
#' @return the probability density of the value of x
#' @examples
#' \dontrun{
#' f(4)
#' }
#' @export
f <- function(x) {
    .Call('_StatComp20076_f', PACKAGE = 'StatComp20076', x)
}

#' @title An Rcpp function for  generating the standard Laplace distribution
#' @description An Rcpp function for  generating the standard Laplace distribution
#' @param x0 the initial value
#' @param sigma the param of Laplace distribution
#' @param N the sample size
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rwMetropolis(.2,5,3000)
#' }
#' @export
rwMetropolis <- function(sigma, x0, N) {
    .Call('_StatComp20076_rwMetropolis', PACKAGE = 'StatComp20076', sigma, x0, N)
}

